import Head from "next/head";
import LiveCaseUpdates from "~/components/LiveCaseUpdates";
import RecentCases from "~/components/RecentCases";

export default function Cases() {
  return (
    <>
      <Head>
        <title>Record Warden - Cases</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecentCases />
      <LiveCaseUpdates />
    </>
  );
}
